name: ai_doctor_app
description: A styled frontend for an AI Doctor app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ionicons: ^0.2.2
  google_fonts: ^6.1.0
  firebase_auth: ^5.7.0
  firebase_core: ^3.0.0
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.2
  sign_in_with_apple: ^5.0.0
  font_awesome_flutter: ^10.1.0 #


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
flutter:
  uses-material-design: true
