name: ai_doctor_app
description: AI Doctor Flutter App (No Firebase)
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Utility
  logger: ^2.0.2
  cupertino_icons: ^1.0.6
  file_picker: ^6.1.1
  image_picker: ^1.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  flutter_sound: ^9.3.9
  url_launcher: ^6.2.6

  # State management (optional but useful)
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
